name: Docker Bild Photo.Api

on:
  push:
    branches:
      - dev
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "DOCKER_TAG=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == feature/* ]]; then
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build coffeepeek.photo.api Docker image
        run: docker build -t winststreloc/coffeepeek.photo.api:${DOCKER_TAG} -f CoffeePeek.Photo.Api/Dockerfile .

      - name: Push coffeepeek.photo.api Docker image
        run: docker push winststreloc/coffeepeek.photo.api:${DOCKER_TAG}
